language: ruby
sudo: false
rvm:
  - 2.2
  - 2.3
script:
  - bundle exec jekyll build
branches:
  only:
  - master
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
