# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Gabriel Stefanini"
author: g4brielvs
description: "Speculations of a humble mammal regarding Life, the Universe and Everything"
baseurl : ""
url: "http://g4brielvs.me/"

google_analytics: "UA-66296217-1"
disqus_shortname: "g4brielvs"

# Handling Reading
include:
  - _pages
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
  - LICENSE
  - docker-compose.yml

  # Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-redirect-from

# Outputting
permalink: /:year/:month/:day/:title/
paginate: 3
paginate_path: /:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  # _posts
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

sass:
  sass_dir: _sass
  style: compressed

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
